# use the nvidia card, not the intel one
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

#reassign right alt to windows and keep it out of mod1 group
xmodmap -e "keycode 108 = Super_L"
xmodmap -e "remove mod1 = Super_L"

#switch statement for starting desktop
case $WM in
enlightenment)
  exec enlightenment_start
 	;;
lxqt)
  exec startlxqt 
  ;;
dwm)
  slstatus &
  feh --bg-scale /home/dylan/Documents/My Pictures/wallpaper/wall8.jpg
  exec dwm
  ;;
*)
  slstatus &
  feh --bg-scale /home/dylan/Documents/My Pictures/wallpaper/wall8.jpg
  exec dwm
  ;;
esac
