# use the nvidia card, not the intel one
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

# disable screen blanking
xset s off
xset s noblank

# reassign right alt to windows and keep it out of mod1 group
xmodmap -e "keycode 108 = Super_L"
xmodmap -e "remove mod1 = Super_L"

# also reassign caps lock to escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# switch statement for starting desktop
case $WM in
dwm-compositing)
  slstatus > /dev/null 2>&1 &
  feh --bg-fill $WALL
  exec dwm
  ;;
dwm)
  slstatus > /dev/null 2>&1 &
  feh --bg-fill $WALL 
  exec dwm
  ;;
*)
  slstatus > /dev/null 2>&1 &
  feh --bg-fill $WALL
  exec dwm
  ;;
esac
